name: backend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.BACKEND_SECRET }}" >> .env
          echo "${{ secrets.EXTRACTOR_SECRET }}" >> .env
      - name: Restart services
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose down || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose up -d
