name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      

      - name: add venv
        run: |
          python3 -m venv .venv
          

      - name: python venv
        run: |
          . .venv/bin/activate
          source .venv/bin/activate
      - name: install dependencies
        run: |
          . .venv/bin/activate
            yarn deploy:install
      - name: Add .env file
        run: |
          . .venv/bin/activate
          touch ./packages/backend/.env
          echo "${{ secrets.BACKEND_SECRET }}" >> ./packages/backend/.env
          echo "${{ secrets.EXTRACTOR_SECRET }}" >> ./packages/extractor/.env
        
      - name: start
        run: |
          . .venv/bin/activate
            RUNNER_TRACKING_ID="" && yarn deploy:start &

     