name: backend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.BACKEND_SECRET }}" >> ./packages/backend/.env
          echo "${{ secrets.EXTRACTOR_SECRET }}" >> ./packages/extractor/.env
      - name: Restart services
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose down || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose up -d --build
