name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

   
      - name: python venv
        run: source .venv/bin/activate
      - name: install dependencies
        run: yarn deploy:install
      - name: runnng go backend
        run: cd packages/backend go run main.go
      # - name: install python dependencies
      #   run: cd packages/extractor && pip install -r requirements.txt
      - name: running python backend
        run: cd packages/extractor && python3 app.py
     