name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: add venv
        run: python3 -m venv .venv
      - name: python venv
        run: |
          . .venv/bin/activate
          source .venv/bin/activate
      - name: install dependencies
        run: |
          . .venv/bin/activate
            yarn deploy:install
      - name: Add .env file
        run: |
          touch ./packages/backend/.env
          echo "BACKEND_SECRET=${{ secrets.BACKEND_SECRET }}" >> ./packages/backend/.env
          echo "EXTRACTOR_SECRET=${{ secrets.EXTRACTOR_SECRET }}" >> ./packages/extractor/.env
        
      - name: start
        run: yarn deploy:start

     