name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: add venv
      #   run: |
      #     python3 -m venv .venv

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          yarn extractor:install

      - name: insall go dependencies
        run: |
          yarn backend:install
      - name: Add .env file
        run: |
          touch ./packages/backend/.env
          echo "${{ secrets.BACKEND_SECRET }}" >> ./packages/backend/.env
          echo "${{ secrets.EXTRACTOR_SECRET }}" >> ./packages/extractor/.env
      - name: starting extractor
        run: yarn extractor:start
      - name: starting backend
        run: yarn backend:start
